### ISSUE TITLE
include gmonitoring subpackage from nfs-ganesha V6.0

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-container#2235]
nfs-ganesha 6.0 includes a new `gmonitoring` RPM. Would you please include this in the upstream container image for squid and newer?

**Comment by ktdreyer** [comment]
I think this means editing `ceph-releases/squid/centos/__GANESHA_PACKAGES__`.

@kalebskeithley created this new package, so he can provide guidance.

**Comment by kalebskeithley** [comment]
??? I didn't create it, ganesha upstream created it.  What guidance do you need from me? I know nothing about containerizing it. Whatever magic you do, where ever you do it, to install the other ganesha packages in a container, add the gmonitoring rpm too.

**Comment by ktdreyer** [comment]
@kalebskeithley who is the lead developer for this `gmonitoring` package?

**Comment by guits** [comment]
> nfs-ganesha 6.0 includes a new `gmonitoring` RPM. Would you please include this in the upstream container image for squid and newer?

@ktdreyer I'm a bit confused. `squid` ships nfs-ganesha 5 at the moment, do we want to bump to 6?

**Comment by ktdreyer** [comment]
That's righ.

**Comment by ktdreyer** [comment]
Resolved in https://github.com/ceph/ceph-container/pull/2238

**Comment by guits** [comment]
> > nfs-ganesha 6.0 includes a new `gmonitoring` RPM. Would you please include this in the upstream container image for squid and newer?
> 
> @ktdreyer I'm a bit confused. `squid` ships nfs-ganesha 5 at the moment, do we want to bump to 6?

@ktdreyer looks like that bump to nfs-ganesha v6 broke squid deployments:


```console
Sep 25 15:47:37 debug-nfs-ganesha-v6-squid-1 ceph-30fb9644-7b55-11ef-b480-5254007a4c9e-mgr-debug-nfs-ganesha-v6-squid-1-xbzxya[32356]: 2024-09-25T15:47:37.762+0000 7f65c03fa640 -1 log_channel(cephadm) log [ERR] : Failed while placing nfs.foo.0.0.debug-nfs-ganesha-v6-squid-1.kwlffn on debug-nfs-ganesha-v6-squid-1: grace tool failed: rados_pool_create: -1
Sep 25 15:47:37 debug-nfs-ganesha-v6-squid-1 ceph-30fb9644-7b55-11ef-b480-5254007a4c9e-mgr-debug-nfs-ganesha-v6-squid-1-xbzxya[32356]: Can't connect to cluster: -1
```

**Comment by dmick** [comment]
@guits do we think this bug about prctl PR_SET_IO_FLUSHER still exists in nfs-ganesha 6 in the container context at least?

**Comment by guits** [comment]
@dmick i think so

**Comment by guits** [comment]
nfs-ganesha 6.1 which is available has fixes for this issue
